### PR TITLE
update to nushell 0.84.1 + new record api

### PR DESCRIPTION
**Pull request by fdncred**
This PR updates your plugin to support nushell 0.84.1 with it's new record api. I realize you may not accept this PR since it points to a development nushell version, but it could still be used to help you understand what changes need to be made to support that latest dev version of nushell.

### CODE REVIEW

**Comment by cptpiepmatz** [comment]
Thanks,
it is a bit hard to look at the changes since you ran some formatting that is not mine.

But other than that, the important change is the use of the `record!` macro in `theme.rs`, right?

**Comment by fdncred** [comment]
> it is a bit hard to look at the changes since you ran some formatting that is not mine.

Yup, it's called `cargo fmt` and comes with rust. It's what we use on nushell.

> But other than that, the important change is the use of the record! macro in theme.rs, right?

Yup, that's right.

**Comment by cptpiepmatz** [comment]
> Yup, it's called `cargo fmt` and comes with rust. It's what we use on nushell.

Maybe it did not respect my `rustfmt.toml` correctly.

Is the macro new in `1.84.0` or in `1.84.1`?

**Comment by fdncred** [comment]
The nushell macro `record!` is new to `0.84.1`.

**Pull request merged**
